### ISSUE TITLE
Styling problem on timeline exercise in lesson 4

### ISSUE THREAD

**Issue by marcvc** [fullstackreact/30-days-of-react#11]
I am currently working on lesson 4 in the book, and the react part of it is working properly, but I'm having problems with the styling? Where can I find the correct css-files to make the app look like it does in the book? 
Thanks a lot! 

Kind regards, 
Marc

**Comment by bcuz** [comment]
Seriously!

**Comment by duanbowen** [comment]
I have the same problem, did you solve it? @marcvc

**Comment by bcuz** [comment]
@duanbowen i ditched the course because of this. bad user experience

**Comment by auser** [comment]
We've updated the course to include all the CSS. We'll push an update with all the styles updated soon!
