### ISSUE TITLE
babel-core/browser.min.js is deprecated and should no longer be part of the course

### ISSUE THREAD

**Issue by interglobalmedia** [fullstackreact/30-days-of-react#17]
Hi,

The `<script src="https://npmcdn.com/babel-core@5.8.38/browser.min.js"></script>` has been deprecated for a while and should no longer be part of the course. It has been replaced with babel-standalone. Like to repo here along with info about browser.min.js:  https://github.com/babel/babel-standalone

In fact, if you use the latest babel-standalone cdn instead, it will work just fine. However, you get the following warning in the console: 

babel.min.js:24 You are using the in-browser Babel transformer. Be sure to precompile your scripts for production - https://babeljs.io/docs/setup/

Therefore, shouldn't you add in the documentation that this use of script tags instead of modern workflows using npm etc. is outdated? And even add the warning that appears when babel-standalone is used? Otherwise it could be misleading or confusing for first time React learners.

**Comment by auser** [comment]
Thanks for the comment! I've updated the course and it will be included in the next update!

**Comment by Nogaeman** [comment]
i have problem, 
You are using the in-browser Babel transformer. Be sure to precompile your scripts for production - https://babeljs.io/docs/setup/

when browse page create by react.js
