### ISSUE TITLE
Missing step between Day 4 to Day 5 - Node and module bundler set up? 

### ISSUE THREAD

**Issue by dominic-taylor** [fullstackreact/30-days-of-react#19]
The code in the repo and the code in the post.md/website examples are different. Up until Day 4 it seemed the React components were put inside `<script>` tags in index.html, with cdn links to React and Babel.  

Then in Day 5 the `<Header />` code examples change unexpectedly and start using " import React from 'react' " which suggests there was a step where a module bundler was set up. 

Maybe this is explained elsewhere but following Day 4 to Day 5 I was confused and comments on the webpage show others were as well.

**Comment by auser** [comment]
Hey @dominic-taylor 

Thanks for reporting. I'm updating it right now and will include a section (a bit later) about setting up the node modules.

Thanks for reporting!

**Comment by auser** [comment]
Fixed this and updating!
