### ISSUE TITLE
Day 5: "recall we defined <Header /> component" quotes changed (not original) code

### ISSUE THREAD

**Issue by MikeTheCanuck** [fullstackreact/30-days-of-react#23]
Near the beginning of [Day 5](https://www.fullstackreact.com/30-days-of-react/day-5/) the text says "Recall we defined <Header /> component as" and displays the following (unstyled) code:

```
class Header extends React.Component {
  render() {
    return (
      <div className="header">
        <div className="menuIcon">
          <div className="dashTop"></div>
          <div className="dashBottom"></div>
          <div className="circle"></div>
        </div>

        <span className="title">
          {this.props.title}
        </span>

        <input
          type="text"
          className="searchInput"
          placeholder="Search ..." />

        <div className="fa fa-search searchIcon"></div>
      </div>
    )
  }
}
```

I believe the `{this.props.title}` is an unintentional inclusion of the *fix* to the previously-hard-coded code.  I had to very closely read and re-read the Day 5 lesson to make sure I inferred what was being taught here, because that's not where my code (leftover from Day 4) started out, and while I know I'm no guru, I found it more confusing than I think is the author's intent.

And when I reference [Day 4](https://www.fullstackreact.com/30-days-of-react/day-4/)'s <Header /> code, it's different in at least a couple of ways:

```
class Header extends React.Component {
  render() {
    return (
      <div className="header">
        <div className="fa fa-more"></div>

        <span className="title">Timeline</span>

        <input
          type="text"
          className="searchInput"
          placeholder="Search ..." />

        <div className="fa fa-search searchIcon"></div>
      </div>
    )
  }
}
```

Not only does this Day 4 code show `<span className="title">Timeline</span>`, but the className "fa fa-more" in Day 4 becomes "menuIcon" in Day 5 [or some other kind of transformation].

If I had to guess, I'd imagine these details are the result of multiple refactorings of the code over the generations of this amazing series.  I hope this helps reduce confusion for future readers.

**Comment by auser** [comment]
Thanks for the compliments! I'll go through that and update it
