### ISSUE TITLE
Yarn start requets html file

### ISSUE THREAD

**Issue by diomededavid** [fullstackreact/30-days-of-react#32]
Yarn start requests html file. 

Error that is returned is:
⠋ Processing src/styles/index.cssCould not find a required file.
  Name: index.html
  Searched in: /Users/daviddiomede/Downloads/30-days-of-react-master/day-1/public
error Command failed with exit code 1.

**Comment by jashmenn** [comment]
Yes, this is weird. We'll fix it, but closing in favor of https://github.com/fullstackreact/30-days-of-react/issues/46
