### ISSUE TITLE
Day 6 lesson missed getdate() definition

### ISSUE THREAD

**Issue by cmarchena** [fullstackreact/30-days-of-react#42]
This lesson has three problems IMHO:
1. When defining initial state, there is no explanation about getTime(). It's on 30-days-of-react/day-6/src/components/Timer/Clock.js but is not inside the lesson
2. The text says: 

>  If we render our new Clock component, we will only get a time rendered everytime the component itself rerenders. It's not a very useful clock (yet). In order to convert our static time display Clock component into a clock that displays the time, we'll need to update the time every second.
> In order to do that, we'll need to track the current time in the state of the component. To do this, we'll need to set an initial state value.
>
Nevertheless, if you follow the instructions provided, you will never see the clock ticking since there are no lifecycles defined. Although the text clearly states that lifecycles will be explained in the next lesson, I think that a better explanation of lesson outcome is required.
3. There are 2 javascript files at 30-days-of-react/day-6/src/components/Timer/ that are almost identical, changing only at line 44
Clock.js 
` hours == 0 ? 12 :`
Timer1.js
`hours === 0 ? 12 :`
which is the correct version because with the first version, the console send this warning:
`./src/Clock.js
  Line 40:  Expected '===' and instead saw '=='  eqeqeq` 
Javascript knowledge for this book is required but if people get frustated on day 6 due to unclear instructions they will not complete the whole book.
Kind regards

**Comment by diamondman** [comment]
Agreed. I was having a real good time with this book right up until I hit chapter 6 and ended up going to the react documentation directly. I will keep reading it, but a lot of this chapter needs to be cleaned up like you said. Maybe once I finish it I can make a PR.
