### ISSUE TITLE
Build error - day 1

### ISSUE THREAD

**Issue by pizzamx** [fullstackreact/30-days-of-react#50]
$ yarn install
yarn install v1.15.2
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/caniuse-api/-/caniuse-api-1.6.0.tgz: Request failed \"404 Not Found\"".
info If you think this is a bug, please open a bug report with the information provided in "/Users/***/git_home/30-days-of-react/day-01/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

And the resource is indeed not available as of now. What should I do?

**Comment by CleverOscar** [comment]
Has this gotten resolved? As of today, I am having this same issue when I am trying to build. I am trying to see if I can figure out the bug and have tried almost all the Yarn CLI and no success. If I get this resolved or if anyone solves this issue please let us know! I would love to work on this

**Comment by pozymasika** [comment]
Removed the build process from day 1 since it hasn't been introduced yet. You can just open the `index.html` file found in `day-01` folder [here](https://github.com/fullstackreact/30-days-of-react/blob/master/day-01/public/index.html) in your browser to view the code results
