### ISSUE TITLE
CSS file is missing

### ISSUE THREAD

**Issue by Melvottero** [fullstackreact/30-days-of-react#81]
I am following along your 30 days of React tutorial, however I could not
find the css-file on day 4. The link you provided gave me an 404 error:
https://github.com/fullstackreact/30-days-of-react/blob/master/day-04/src/components/Timeline/Timeline.css

Could you direct me to the correct css-file or even better fix the link
on the webpage so that others could follow along :)?

Thank you so much and keep up the great work,

HelpScout URL: https://secure.helpscout.net/conversation/1164238631/40426?folderId=790126

**Comment by pozymasika** [comment]
@jashmenn updated the links, you can rebuild for the website
